### ISSUE TITLE
TODO before and after HOHQMesh and HOHQMesh_jll become registered packages

### ISSUE THREAD

**Issue by sloede** [trixi-framework/HOHQMesh.jl#1]
Right now, there are a few quirks that result from HOHQMesh and HOHQMesh_jll not being registered packages. These should be removed once they are available in the general registry.

Once `HOHQMesh_jll` is a registered package:
- [x] Remove main `Manifest.toml`
- [x] Remove `HOHQMesh_jll` dependency from `docs/Project.toml`
- [x] Use normal workflow in `.github/workflows/Documenter.yml`

Once `HOHQMesh` is a registered package:
- [x] Make `stable` the canonical URL in `docs/make.jl`
- [x] Update README.md:
  - [x] installation procedures
  - [x] Link to `stable` docs
- [x] Change main link to `stable` docs

**Comment by andrewwinters5000** [comment]
@sloede I believe all points are this checklist have been handled. Should we close this issue?

**Comment by sloede** [comment]
I agree!
